### PR TITLE
Dirac Operator in Componentwise Ordering

### PR DESCRIPTION
**Pull request by tmattha**
- Implements the Dirac operator using arrays in componentwise ordering.
- Adds reordering of relevant arrays (as a copy).
- Adds functions to change ordering from componentwise to chunkwise and vice versa.
- Adds gtest/rapidcheck as a testing framework.
- Add integration tests for a c_sw value of 0 (i.e. phi is scaled by different functions).
- Fixes bad outputfile paths.
- Changes clang-format column limit to 80. 100 characters was often too wide for side-by-side editing in VS Code or in the terminal. This was not applied everywhere, but should be in the future.

### CODE REVIEW

**Comment by Gustavroot** [comment]
After cloning, copying the MakeSettings file, and disabling unit tests compilation (one step at a time), I compiled with make and all good. I'm doing this on JUWELS directly.

My first point is : there's quite some warnings in the compilation. Should this be treated now, or are they mostly irrelevant at the moment?

Results with 96x32^3 (2 nodes) : works both with CUDA_ENABLER=yes and CUDA_ENABLER=no.

Results with 144x48^3 (6 nodes) : pending .. taking forever for the job to go through. I'll update things here as soon as this runs

**Comment by tmattha** [comment]
@Gustavroot 

About the warnings. I generally like to fix them immediately so they don't pile up. However, I did not manage to integrate DDalphaAMGs Makefile-based build system in VS Code properly so I was always missing per-file warnings.

If the warnings are from changed code, sure, let's fix them. If not I suggest this should be done in some concentrated cleanup effort. Also warnings from compiling C code with g++ can probably stay.

Maybe we have a look at those from the default set (i.e. not with `-Wall`) and try to figure out if those are in changed source code?

**Comment by tmattha** [comment]
Hey @Gustavroot, I dug through the compiler warnings. NVCC is now free of warnings (there was one), and I also fixed a linker warning. The rest comes from the original C code. Mostly pointer type and const qualifier warnings. Can probably be easily fixed separately. Doxygen throws warnings, but I guess that's normal.

**Comment by Gustavroot** [comment]
I think we're good to go then with this PR. The 144x48^3 will come later anyways, in a more thorough context, but the 96x32^3 are good enough I think

**Pull request merged**
